version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
    environment:
      MONGO_URI: 'mongodb://mongodb:27017/poll'
    networks:
      - app-network

  mongodb:
    image: mongo:latest 
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
